# -*- coding: utf-8 -*-
"""Assessment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-TeiKETplv5m9uQX88QQS_RaJxOMdyB

1. Import Libraries
"""

import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import f1_score

# Models
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

"""2. Load Dataset"""

train = pd.read_csv('/content/train_LZdllcl.csv')
test = pd.read_csv('/content/test_2umaH9m.csv')
sample = pd.read_csv('/content/sample_submission_M0L0uXE.csv')

print(train.shape, test.shape)
train.head()

"""3. Basic EDA"""

print(train.info())
print(train.describe())

# Target distribution
sns.countplot(x='is_promoted', data=train)
plt.show()

# Missing values
print(train.isnull().sum())

"""4. Data Preprocessing"""

# 4.1 Handle Missing Values


# Fill education with mode
train['education'].fillna(train['education'].mode()[0], inplace=True)
test['education'].fillna(test['education'].mode()[0], inplace=True)

# Fill previous_year_rating with median
train['previous_year_rating'].fillna(train['previous_year_rating'].median(), inplace=True)
test['previous_year_rating'].fillna(test['previous_year_rating'].median(), inplace=True)

# 4.2 Encode Categorical Variables


cat_cols = ['department', 'region', 'education', 'gender', 'recruitment_channel']

for col in cat_cols:
    le = LabelEncoder()
    combined = pd.concat([train[col], test[col]])
    le.fit(combined)

    train[col] = le.transform(train[col])
    test[col] = le.transform(test[col])

"""Adding more Featues"""

train['total_score'] = train['avg_training_score'] * train['no_of_trainings']
test['total_score'] = test['avg_training_score'] * test['no_of_trainings']

train['service_age_ratio'] = train['length_of_service'] / train['age']
test['service_age_ratio'] = test['length_of_service'] / test['age']

# KPI + training interaction
train['kpi_training'] = train['KPIs_met >80%'] * train['avg_training_score']
test['kpi_training'] = test['KPIs_met >80%'] * test['avg_training_score']

# Strong performance indicator
train['overall_performance'] = (
    train['KPIs_met >80%'] * 2 +
    train['awards_won?'] * 3 +
    train['avg_training_score'] / 10
)

test['overall_performance'] = (
    test['KPIs_met >80%'] * 2 +
    test['awards_won?'] * 3 +
    test['avg_training_score'] / 10
)

# Experience vs performance
train['exp_performance'] = train['length_of_service'] * train['avg_training_score']
test['exp_performance'] = test['length_of_service'] * test['avg_training_score']

# Training efficiency
train['training_efficiency'] = train['avg_training_score'] / (train['no_of_trainings'] + 1)
test['training_efficiency'] = test['avg_training_score'] / (test['no_of_trainings'] + 1)

# Promotion likelihood score
train['promotion_score'] = (
    train['avg_training_score'] +
    train['previous_year_rating'] * 10 +
    train['KPIs_met >80%'] * 20
)

test['promotion_score'] = (
    test['avg_training_score'] +
    test['previous_year_rating'] * 10 +
    test['KPIs_met >80%'] * 20
)

train['exp_bucket'] = pd.cut(train['length_of_service'], bins=[0,3,7,20], labels=[0,1,2])
test['exp_bucket'] = pd.cut(test['length_of_service'], bins=[0,3,7,20], labels=[0,1,2])

train['exp_bucket'] = train['exp_bucket'].cat.add_categories([-1]).fillna(-1).astype(int)
test['exp_bucket'] = test['exp_bucket'].cat.add_categories([-1]).fillna(-1).astype(int)

train['rating_kpi'] = train['previous_year_rating'] * train['KPIs_met >80%']
test['rating_kpi'] = test['previous_year_rating'] * test['KPIs_met >80%']

train['high_performer'] = (
    (train['previous_year_rating'] >= 4) &
    (train['KPIs_met >80%'] == 1)
).astype(int)

test['high_performer'] = (
    (test['previous_year_rating'] >= 4) &
    (test['KPIs_met >80%'] == 1)
).astype(int)

# 4.3 Feature & Target Split

X = train.drop(['employee_id', 'is_promoted'], axis=1)
y = train['is_promoted']

test_ids = test['employee_id']
X_test = test.drop(['employee_id'], axis=1)

"""5. Train-Test Split"""

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Check imbalance
print(y.value_counts())

# Compute scale_pos_weight
neg = y.value_counts()[0]
pos = y.value_counts()[1]

scale_pos_weight = neg / pos
print("Scale Pos Weight:", scale_pos_weight)

# GRID SEARCH CV

param_grid = {
    'max_depth': [4, 5, 6],
    'n_estimators': [300, 400],
    'learning_rate': [0.03, 0.05],
    'min_child_weight': [1, 2],
    'subsample': [0.8],
    'colsample_bytree': [0.8]
}

xgb = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

grid = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    scoring='f1',
    cv=3,
    verbose=1
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV F1 Score:", grid.best_score_)

# BEST MODEL


model = grid.best_estimator_
model

# 12. THRESHOLD TUNING


probs = model.predict_proba(X_val)[:, 1]

best_f1 = 0
best_thresh = 0.5

for t in np.arange(0.1, 0.6, 0.01):
    preds = (probs > t).astype(int)
    score = f1_score(y_val, preds)

    if score > best_f1:
        best_f1 = score
        best_thresh = t

print("Best Threshold:", best_thresh)
print("Validation F1 Score:", best_f1)

# 13. FINAL MODEL TRAINING

model.fit(X, y)

# 14. TEST PREDICTION
# ==============================

test_probs = model.predict_proba(X_test)[:, 1]
test_preds = (test_probs > best_thresh).astype(int)

y_pred = model.predict(X_val)

from sklearn.metrics import f1_score
f1_score(y_val, y_pred)

import xgboost as xgb
import matplotlib.pyplot as plt

xgb.plot_importance(model)
plt.show()

"""The model was built using XGBoost with feature engineering and hyperparameter tuning to predict employee promotions. Threshold tuning was applied, but the default model predictions achieved a better F1 score of approximately 0.48, indicating moderate performance on this imbalanced dataset. Overall, the model can help identify potential candidates for promotion"""

# 15. CREATE SUBMISSION FILE
# ==============================

submission = pd.DataFrame({
    'employee_id': test_ids,
    'is_promoted': test_preds
})
submission

submission.to_csv("submission.csv", index=False)

print("✅ Submission file created successfully!")